apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-docs
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-docs
  template:
    metadata:
      labels:
        app: cluster-docs
    spec:
      containers:
        - name: cluster-docs
          image: ghcr.io/nst-sdc/nst-cluster-docs:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-docs
  namespace: apps
spec:
  selector:
    app: cluster-docs
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-docs-ing
  namespace: apps
spec:
  ingressClassName: traefik
  rules:
    - host: docs.nstsdc.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cluster-docs
                port:
                  number: 80
